services:
  openvpn:
    build: .
    container_name: openvpn
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      - net.ipv4.ip_forward=1
    ports:
      - "2402:2402/udp"
    volumes:
      - ./server.conf:/etc/openvpn/server/server.conf:ro
      - ./ldap.conf:/etc/openvpn/auth/ldap.conf:ro
      - ./openvpn_data/easy-rsa:/etc/openvpn/easy-rsa
      - ./openvpn_data/log:/var/log/openvpn
    command: ["/start.sh"]

  openldap:
    image: bitnami/openldap:2.6.9
    container_name: openldap
    # ports:
    #   - "1389:1389"
    #   - "1636:1636"
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=openvpn
      - LDAP_PASSWORDS=openvpn
      - LDAP_ROOT=dc=example,dc=org
    volumes:
      - ./openldap_data:/bitnami/openldap
