services:
  openvpn:
    build: .
    container_name: openvpn
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      - net.ipv4.ip_forward=1
    ports:
      - "2402:2402/udp"
    volumes:
      - ./server.conf:/etc/openvpn/server/server.conf:ro
      - ./data/easy-rsa:/etc/openvpn/easy-rsa
      - ./data/log:/var/log/openvpn
    command: ["/start.sh"]
